import { defineConfig } from 'tsup';

export default defineConfig({
  entry: [
    'src/index.ts',
    'src/storage/index.ts',
    'src/network/index.ts',
    'src/outbox/index.ts',
    'src/sync/index.ts',
    'src/client/index.ts',
    'src/testing/index.ts',
  ],
  format: ['esm'],
  dts: true,
  clean: true,
  sourcemap: true,
  target: 'es2022',
  esbuildOptions(options) {
    options.banner = {
      js: '// @generated by Offline Sync Engine SDK',
    };
  },
});
