import { defineConfig } from 'tsup';

export default defineConfig({
  entry: ['src/index.ts'],
  format: ['esm'],
  dts: false,
  clean: true,
  sourcemap: true,
  target: 'node22',
  esbuildOptions(options) {
    options.banner = {
      js: '// @generated by Offline Sync Engine Server',
    };
  },
});
